## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    - repository: helmfileconfig
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/techradar-helm-config

trigger:
  tags:
    include:
    - "*"
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - main

extends:
  template: pipelines/build-api/v1.yml@templates
  parameters:
    gitVersionSpec: '6.x'
    buildProject: src/**/*.csproj
    publishProject: src/Spydersoft.TechRadar.Data.Api.csproj
    netCoreVersion: '8.0.x'
    artifactName: techradarDataApi
    artifactZipName: Spydersoft.TechRadar.Data.Api
    dockerImageName: spydersoft/techradar/techradar.data.api
    dockerFilePath: Dockerfile
    imageTagVariableName: data_api
    helmfileRepoName: helmfileconfig
    execute_sonar: true
    #if it's a PR or build from main, don't update helmfile config or build/publish docker image
    ${{ if or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main')) }}:
      updateHelmConfig: false
      buildAndPublishDockerImage: false
    ${{ else }}:
      updateHelmConfig: true
      buildAndPublishDockerImage: true
    sonar_endpoint_name: sonarcloud-spydersoft
    sonar_project_key: spydersoft-consulting_techradar-data-api
    sonar_project_name: techradar-data-api
    execute_tests: true
    test_projects: '**/*.Tests/*.csproj'
    use_sonarcloud: true
    sonar_cloud_organization: spydersoft-consulting