## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    - repository: helmfileconfig
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/techradar-helm-config

trigger:
  tags:
    include:
    - "*"
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - main

extends:
  template: pipelines/build-api/v1.yml@templates
  parameters:
    gitVersionSpec: '6.x'
    buildProject: src/**/*.csproj
    publishProject: src/Spydersoft.TechRadar.Data.Api.csproj
    netCoreVersion: '8.0.x'
    artifactName: techradarDataApi
    artifactZipName: Spydersoft.TechRadar.Data.Api
    dockerImageName: spydersoft/techradar/techradar.data.api
    dockerFilePath: Dockerfile
    imageTagVariableName: data_api
    helmfileRepoName: helmfileconfig
    executeSonar: true
    #if it's a PR or build from main, don't update helmfile config or build/publish docker image
    ${{ if or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main')) }}:
      updateHelmConfig: false
      buildAndPublishDockerImage: false
    ${{ else }}:
      updateHelmConfig: true
      buildAndPublishDockerImage: true
    sonarEndpointName: sonarcloud-spydersoft
    sonarProjectKey: spydersoft-consulting_techradar-data-api
    sonarProjectName: techradar-data-api
    executeTests: true
    testProjects: '**/*.Tests/*.csproj'
    useSonarCloud: true
    sonarCloudOrganization: spydersoft-consulting