## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    # - repository: helmfileconfig
    #   type: github
    #   endpoint: spydersoft-gh
    #   name: spyder007/techradar-helm-config

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr: none

extends:
  template: pipelines/build-api/v1.yml@templates
  parameters:
    buildProject: src/**/*.csproj
    publishProject: src/Spydersoft.TechRadar.Data.Api.csproj
    netCoreVersion: '8.0.x'
    artifactName: techradarDataApi
    artifactZipName: Spydersoft.TechRadar.Data.Api
    dockerImageFileName: techradar_data_api
    dockerImageName: spydersoft/techradar/techradar.data.api
    dockerFilePath: Dockerfile
    imageTagVariableName: techradar_data_api
    helmfileRepoName: helmfileconfig
    execute_sonar: false
    updateHelmConfig: false
    #sonar_endpoint_name: ${{ parameters.sonar_endpoint_name }}
    #sonar_project_key: ${{ parameters.sonar_project_key }}
    #sonar_project_name: ${{ parameters.sonar_project_name }}
    #execute_tests: ${{ parameters.execute_tests }}
    #test_projects: ${{ parameters.test_projects }}
    #use_sonarcloud: ${{ parameters.use_sonarcloud }}
    #sonar_cloud_organization: ${{ parameters.sonar_cloud_organization }}